version: "3.4"
services:
  postgres:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=soy
    ports:
      - "54320:5432"
    expose:
      - "54320"
    volumes:
      - ../shared/postgres-data:/var/lib/postgresql/data

  dbFiller:
    image: dbfiller
    expose:
      - "5005"
    ports:
      - "5005:5005"
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "-jvm-debug", "5005", "~run"]
    volumes:
      - ../dbFiller/src:/app/src
      - ../dbFiller/build.sbt:/app/build.sbt
      - ../dbFiller/train.csv:/app/train.csv
