version: "3.4"

services:
  postgres:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=soy
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "54320:5432"
    expose:
      - "54320"
    volumes:
      - ../shared/postgres-data:/var/lib/postgresql
      - ../shared/postgres-data/migrations/001-createTableSoy.sql:/docker-entrypoint-initdb.d/001-createTableSoy.sql

  dbFiller:
    image: dbfiller
    expose:
      - "5005"
    ports:
      - "5005:5005"
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "-jvm-debug", "5005", "~run"]
    volumes:
      - ../dbFiller/src:/app/src
      - ../dbFiller/build.sbt:/app/build.sbt
      - ../dbFiller/train.csv:/app/train.csv

  soyApi:
    image: soyapi
    expose:
      - "5005"
    ports:
      - "5006:5005"
      - "8080:8080"
    environment:
      - MODEL_INPUT_PATH=/trainer-data/model.pmml
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "-jvm-debug", "5005", "~run"]
    volumes:
      - ../soyApi/src:/app/src
      - ../soyApi/build.sbt:/app/build.sbt
      - ../shared/trainer-data/:/trainer-data

  trainer:
    image: trainer
    expose:
      - "5005"
    ports:
      - "5005:5005"
    environment:
      - MODEL_OUTPUT_PATH=/trainer-data/model.pmml
    volumes:
      - ../trainer/src:/app/src
      - ../trainer/build.sbt:/app/build.sbt
      - ../shared/trainer-data/:/trainer-data
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "run"]

networks:
  default:
  trainer-spark:
