version: "3.4"

x-scalaComponent:
  &scala-component
  depends_on:
    - postgres
  build:
    context: ..
    dockerfile: ./docker/Dockerfile
    target: base
  networks:
    - default

services:
  postgres:
    image: postgres:10.10
    container_name: "postgresSoy"
    networks:
      - default
      - trainer-spark

  dbFiller: *scala-component
  soyApi: *scala-component
  trainer: *scala-component