version: "3.4"
services:
  postgres:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=soy

  dbFiller:
    image: "dbfiller/latest"
    build:
      target: prod
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "project dbFiller", "run"]

  api:
    image: "dbfiller/latest"
    build:
      target: prod
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "project api", "run"]

  trainer:
    image: "trainer/latest"
    build:
      target: prod
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "project trainer", "run"]