version: "3.4"

x-scalaComponent:
  &scala-component
  depends_on:
    - postgres
  build:
    context: ..
    dockerfile: ./docker/Dockerfile
    target: base

services:
  postgres:
    image: postgres:10.10
    container_name: "postgresSoy"

  dbFiller: *scala-component