version: "3.4"

services:
  postgres:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=soy
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "54320:5432"
    expose:
      - "54320"
    volumes:
      - ../shared/postgres-data:/var/lib/postgresql
      - ../shared/postgres-data/migrations/001-createTableSoy.sql:/docker-entrypoint-initdb.d/001-createTableSoy.sql

  dbFiller:
    image: dbfiller
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "project dbFiller", "run"]
    volumes:
      - ../commons/src:/app/commons/src/
      - ../dbFiller/src:/app/dbFiller/src/
      - ../project/build.properties:/app/project/build.properties
      - ../project/Common.scala:/app/project/Common.scala
      - ../project/Dependency.scala:/app/project/Dependency.scala
      - ../project/Subproject.scala:/app/project/Subproject.scala
      - ../build.sbt:/app/build.sbt
      - ../train.csv:/app/train.csv

  api:
    image: api
    ports:
      - "8080:8080"
    environment:
      - MODEL_INPUT_PATH=/trainer-data/model.pmml
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "project api", "run"]
    volumes:
      - ../api/src:/app/api/src
      - ../commons/src:/app/commons/src/
      - ../project/build.properties:/app/project/build.properties
      - ../project/Common.scala:/app/project/Common.scala
      - ../project/Dependency.scala:/app/project/Dependency.scala
      - ../project/Subproject.scala:/app/project/Subproject.scala
      - ../shared/trainer-data/:/trainer-data
      - ../build.sbt:/app/build.sbt

  trainer:
    image: trainer
    environment:
      - MODEL_OUTPUT_PATH=/trainer-data/model.pmml
    entrypoint: ["/root/.sdkman/candidates/sbt/current/bin/sbt", "project trainer", "run"]
    volumes:
      - ../commons/src:/app/commons/src/
      - ../project/build.properties:/app/project/build.properties
      - ../project/Common.scala:/app/project/Common.scala
      - ../project/Dependency.scala:/app/project/Dependency.scala
      - ../project/Subproject.scala:/app/project/Subproject.scala
      - ../shared/trainer-data/:/trainer-data
      - ../trainer/src:/app/trainer/src/
      - ../trainer/docker-compose.yml:/app/trainer/docker-compose.yml
      - ../trainer/Dockerfile:/app/trainer/Dockerfile
      - ../build.sbt:/app/build.sbt

networks:
  default:
  trainer-spark:
